name: Rust

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["*"]
  pull_request:
    branches: [develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wireguard-go
        run: brew install wireguard-tools
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features